### ISSUE TITLE
Reprocessing functionality

### ISSUE THREAD

**Issue by adarshp** [clulab/tomcat-text#100]
We should either add an app or extend one of the existing apps to provide reprocessing functionality. That is, as we add new extraction rules and improve existing ones, we will periodically (tentatively on a monthly basis) reprocess `.metadata` files to leverage the outputs of the new and improved rules. The input will be a directory of `.metadata` files, and the output will be a directory of reprocessed `.metadata` files.

Each input `.metadata` file in the input directory will have its contents copied to a corresponding `.metadata` file (with the same filename) in the output directory, but with the existing dialog agent messages replaced with new dialog agent messages produced by reprocessing the `data.text` field in the messages on the `agent/dialog` topic. The `header` and `msg` timestamps for the new dialog agent messages should be copied from the `header` and `msg` timestamps of the original dialog agent messages.

**Comment by jastier** [comment]
Started as tomcat-text branch issue_100_joseph
<https://github.com/clulab/tomcat-text/tree/issue_100_joseph>

**Comment by adarshp** [comment]
Update:

- If a `.metadata` file ends with `Vers-<N>.metadata`, the corresponding file in the output directory should end with `Vers-<N+1>.metadata` (instead of preserving the original filename). This is to comply with the TA3 file naming scheme.

**Comment by adarshp** [comment]
Closed by #126  and #127 .
