### ISSUE TITLE
Agent Info message

### ISSUE THREAD

**Issue by adarshp** [clulab/tomcat-text#101]
With data collection starting soon and the reprocessing capability that will be implemented (#100), it makes sense to add the agent version info message proposed by JCR here:

https://gitlab.asist.aptima.com/asist/testbed/-/blob/develop/MessageSpecs/Agent/versioninfo/agent_versioninfo.md

While this is a draft, I doubt that there will be large changes to the format, so I think we can go ahead and add it.

This message should be published to the message bus whenever there is a trial start message published on the bus.

For now, just include the `agent_name`, `version`, and `owner` fields in the `data` part of the message. We can update the format when it gets finalized in the testbed WG.

**Comment by jastier** [comment]
Started as tomcat-text branch issue_101_joseph
<https://github.com/clulab/tomcat-text/tree/issue_101_joseph>

**Comment by adarshp** [comment]
Closed by #105
