### ISSUE TITLE
Help me build app for evaluating the extractions

### ISSUE THREAD

**Issue by BeckySharp** [clulab/tomcat-text#109]
I added a set of methods in the `eval_app` branch to generate the annotation sheets (https://github.com/clulab/tomcat-text/blob/eval_app/src/main/scala/org/clulab/asist/export/ExtractionEvaluation.scala) and also an app ("apps/RunExtractionEvaluation")

I would love some help @jastier with filling in this: https://github.com/clulab/tomcat-text/blob/eval_app/src/main/scala/org/clulab/asist/apps/RunExtractionEvaluation.scala#L10

specifically, IDK how to specify a directory of input (likely message bus stuff), have it load the messages, run them through the engine, and return the mentions.  likely trivial, but IDK how to do it :)

I think once that's in place the rest is done....

FYI @adarshp @remo-help

**Comment by BeckySharp** [comment]
@jastier @adarshp I think the missing functionality from this is basically (at lay on the backside)  what is going to be done for #100 fyi

**Comment by jastier** [comment]
Did completion of  [Issue #100](https://github.com/clulab/tomcat-text/issues/100) resolve this issue?

**Comment by BeckySharp** [comment]
yes, thanks!
