### ISSUE TITLE
md generation

### ISSUE THREAD

**Issue by BeckySharp** [clulab/tomcat-text#112]
- return string
- return simple map structure for downstream manipulation

**Comment by adarshp** [comment]
A JSON output would be nice if possible, but no worries if that's too difficult.

**Comment by BeckySharp** [comment]
it's not too difficult, but since the method will be used as a library from scala I think it would be easier to not parse json

**Comment by adarshp** [comment]
Sure, makes sense, let's not worry about having JSON output.

**Comment by adarshp** [comment]
@jastier  - could you please update the `processors` version to 8.4.2 to get the changes from https://github.com/clulab/processors/pull/519 ?

I tried just changing the version number in `build.sbt` but got compile errors. I figure it will be quicker if I let you fix them :)

**Comment by jastier** [comment]
Done.  https://github.com/clulab/tomcat-text/pull/121

**Comment by adarshp** [comment]
Closed by #121
