### ISSUE TITLE
Unknown regex issue

### ISSUE THREAD

**Issue by remo-help** [clulab/tomcat-text#114]
For some reason Odin is not picking up regex pattersn with an apostrophe (') in them.
For example: "women's" in "women's" room is not being picked up, the regex pattern for this is /women's room/.
This issue breaks our "rooms_mwe_surface" rule in "locations.yml"

Im not sure whats going on, apostrophes are not special characters in regex...

Replicate error:
- checkout "remo_dev"
- "sbt webapp_run"
- input in text field:
- - "I'm in the boiler room" (this works fine)
- - "I'm in the women's room" (does not work

**Comment by BeckySharp** [comment]
I think this is more an issue with the matches applying to a single token rather than a span of tokens, and I think that when I added the `mwe` rules etc i was mistaken, but i will def look at it

**Comment by BeckySharp** [comment]
ok, so the problem was that the tokenization splits words like "women's" and "ladies'" into two tokens:
`women` + `'s` and  `ladies` + `'` (word + possessive marker)
so I added an optional intervening `[tag=/POS/]?` and it's good

**Comment by BeckySharp** [comment]
![image](https://user-images.githubusercontent.com/5384073/122788137-e37e3e80-d26a-11eb-9302-88de29aa728f.png)

![image](https://user-images.githubusercontent.com/5384073/122788157-e8db8900-d26a-11eb-8a85-d4d36fbd7baa.png)

**Comment by BeckySharp** [comment]
@remo-help I pushed the change, so please take a look and see if this fixes this issue

**Comment by remo-help** [comment]
yes, this works now, thanks!
