### ISSUE TITLE
Agent => attachment action is missing from PR'd code

### ISSUE THREAD

**Issue by BeckySharp** [clulab/tomcat-text#142]
@remo-help I just noticed that the code to actually convert the agent args into Agent attachments isn't in the PR (#140 ), is it no committed or did it get deleted? I can readd it prob but thought it would be easiest to check first.
thanks!

**Comment by remo-help** [comment]
That's not good. I have a hunch why this might be, if so, then it's probably my fault. I'll look into it tomorrow.

**Comment by remo-help** [comment]
I merged main into the branch a  couple of days ago to keep thins up to date and test something. I may have accidentally overwritten something in that process. Would have noticed this normally, but I thought you wrote something to convert the agent attachment back into a normal argument, so it didnt make any difference with the tests.
That's my hypothesis to what happened. I have to look at it tomorrow, already 10pm here

**Comment by BeckySharp** [comment]
sure thing, thanks!
