### ISSUE TITLE
Extend Evaluation App to work on recent additions

### ISSUE THREAD

**Issue by remo-help** [clulab/tomcat-text#152]

**Comment by BeckySharp** [comment]
fyi @remo-help 
Note on **issue 1,  where the rule counts didn't match**.   The code is fine (double checked), what happened is that I regenerated the first sheet a few time for diff reasons, and bc there wasn't a random seed set, we got a diff subset, but I didn't re-upload the summary sheet (my bad).  In the future we need to re-upload/import both.
