### ISSUE TITLE
Set version number from config file

### ISSUE THREAD

**Issue by adarshp** [clulab/tomcat-text#166]
We currently have the version hardcoded in two places:

https://github.com/clulab/tomcat-text/blob/3dfe1978f2d3820a2c0f526ba434a7bfb0162794/src/main/scala/org/clulab/asist/agents/DialogAgent.scala#L60

https://github.com/clulab/tomcat-text/blob/3dfe1978f2d3820a2c0f526ba434a7bfb0162794/scripts/process_extraction_schemas_json#L15

We should instead have a single config file that can be used for setting the version. [Eidos](https://github.com/clulab/eidos) and [Reach](https://github.com/clulab/reach) use a file called `version.sbt` (see here: https://github.com/clulab/eidos/blob/master/version.sbt) - perhaps we can do the same?

**Comment by jastier** [comment]
- Added a file where we can easily set our software version (currently at 2.2.2), "tomcat-text/version.sbt"
- Now when we compile the code, sbt will create a case object that includes build information including the version number from that file.
- The Dialog Agents now set their version number using the new case object.
- Branch version_joseph has these changes and is ready to merge into the master branch.
