### ISSUE TITLE
Additional Keywords by CMU

### ISSUE THREAD

**Issue by aishj10** [clulab/tomcat-text#176]
tools | role | rubble | markers | victim
-- | -- | -- | -- | --
tool | role | gravel | marker | victim
hammer | medic | rubble | mark | critical
durability | specialist | clear | label | person
replenish | searcher | pile | put | patient
equipment | switch | excavate | unmark | save
break | engineer | block | indicate | revive
utility | stretcher |   |   | rescue
kit | heavy |   |   |  
weapon |   |   |   |  
shovel |   |   |   |  
sledgehammer |   |   |   |  
medkit |   |   |   |

**Comment by adarshp** [comment]
Thanks @aishj10 !

@remo-help - are these keywords covered in our system?

**Comment by remo-help** [comment]
thanks @aishj10 
@adarshp most of them are, but a few are not, I'll integrate them into our keywords

**Comment by adarshp** [comment]
Closed by #179
