### ISSUE TITLE
Dockerized chat agent, part 2

### ISSUE THREAD

**Issue by adarshp** [clulab/tomcat-text#18]
@jastier  - nice work on #16 .

The next steps are: 

- [ ] Add a Dockerfile that tells Docker how to build the image.

The last line of this Dockerfile should be:

```Dockerfile
ENTRYPOINT sbt "runMain org.clulab.asist.DialogAgentTest"
```

- [ ] In the `DialogAgent`, configure the subscribe callback to call the [`runExtraction` method](https://github.com/clulab/tomcat-text/blob/1978cafd46d9ea729599da76391e8ebd69a635c6/src/main/scala/org/clulab/asist/Extractor.scala#L106), with the first argument being the text received on the `observations/chat` topic. See [here](https://github.com/clulab/tomcat-text/blob/1978cafd46d9ea729599da76391e8ebd69a635c6/src/main/scala/org/clulab/asist/Extractor.scala#L168) for an example invocation.

- [ ] Create a class called `ChatAnalysisMessage` that has attributes corresponding to the fields here: https://github.com/clulab/tomcat-text/blob/1978cafd46d9ea729599da76391e8ebd69a635c6/src/main/scala/org/clulab/asist/Extractor.scala#L194-L212 that can be populated with some of the code in [`extractMentions`](https://github.com/clulab/tomcat-text/blob/1978cafd46d9ea729599da76391e8ebd69a635c6/src/main/scala/org/clulab/asist/Extractor.scala#L154). The constructor of this class should take whatever arguments it needs to populate the attributes.

- [x] In the `DialogAgent` class, create a `ChatAnalysisMessage` object every time a message is received on the `observations/chat` topic, then use `json4s` to serialize the ChatAnalysisMessage object to JSON (https://github.com/json4s/json4s#serialization) and publish it to the `agent/tomcat_chatbot` topic.

**Comment by jastier** [comment]
This is done.
