### ISSUE TITLE
Adding test for ExtractDirSearch

### ISSUE THREAD

**Issue by adarshp** [clulab/tomcat-text#19]
We should add a test for the ExtractDirSearch app. 

Steps:

- [ ]  `mkdir -p data/test`
- [ ] Add a file `README.md` in the `data/test` directory with the following content:
  *These data were generated by Arizona State University under the DARPA ASIST program and published here for engineering purposes by the ToMCAT project (https://ml4ai.github.io/tomcat, contract no. W911NF2010002) at the University of Arizona.*
- [ ] Add this [Zoom transcript from the ASIST engineering data](https://drive.google.com/file/d/1MF2cMxqIuxekda3vmuPRIgAA5TZPB5qK/view?usp=sharing) to the `data/test` directory.
- [ ] Add a test for the `ExtractDirSearch` app (either as part of `sbt test`, or just a command line invocation of `sbt 'runMain org.clulab.asist.ExtractDirSearch` - see `scripts/run_fall2020_analysis` for an example invocation)

Note: You'll need to run `git add -f data/test/<filename>` to force add the README and the transcript file - the `-f` flag is needed since the top-level .gitignore contains the line `data/*` to prevent accidental addition of large amounts of analysis data.

**Comment by jastier** [comment]
OK, working on it.

**Comment by jastier** [comment]
Done, see master branch update fc2c5a5
