### ISSUE TITLE
multiple repeats of same utterances in metadata

### ISSUE THREAD

**Issue by remo-help** [clulab/tomcat-text#208]
This is in regards to the new data in study 3 pilot (spiral)

I'm currently doing the evaluation with @Yuweien.
It seems that the metadata files continue multiple repeats of the same utterances, is this intended?

For example, try the following file from the google sdk: "study-3_spiral-1_pilot_NotHSRData_TrialMessages_Trial-T000370-aborted_Team-TM000048_Member-na_CondBtwn-ASI-ALL_CondWin-na_Vers-1"

and search for the following string: "matter what kind of victim is in the room"

I get 89 (!) hits

**Comment by Yuweien** [comment]
Yes, I found that too!

**Comment by remo-help** [comment]
@adarshp there seems to be more concrete problem here. Can you confirm that the following files are the ones you wanted us to evaluate:
  "gs://studies.aptima.com/study-3_spiral-1_pilot/NotHSRData_TrialMessages_Trial-T000370-aborted_Team-TM000048_Member-na_CondBtwn-ASI-ALL_CondWin-na_Vers-1.metadata" \
  "gs://studies.aptima.com/study-3_spiral-1_pilot/NotHSRData_TrialMessages_Trial-T000370_Team-TM000048_Member-na_CondBtwn-ASI-ALL_CondWin-na_Vers-1.metadata" \
  "gs://studies.aptima.com/study-3_spiral-1_pilot/NotHSRData_TrialMessages_Trial-T000371_Team-TM000048_Member-na_CondBtwn-ASI-ALL_CondWin-na_Vers-1.metadata" \
  "gs://studies.aptima.com/study-3_spiral-1_pilot/NotHSRData_TrialMessages_Trial-T000373_Team-TM000049_Member-na_CondBtwn-ASI-ALL_CondWin-na_Vers-1.metadata" \
  "gs://studies.aptima.com/study-3_spiral-1_pilot/NotHSRData_TrialMessages_Trial-T000374_Team-TM000049_Member-na_CondBtwn-ASI-ALL_CondWin-na_Vers-1.metadata" \
  "gs://studies.aptima.com/study-3_spiral-1_pilot/NotHSRData_TrialMessages_Trial-T000375_Team-TM000049_Member-na_CondBtwn-ASI-ALL_CondWin-na_Vers-1.metadata" \
  "gs://studies.aptima.com/study-3_spiral-1_pilot/NotHSRData_TrialMessages_Trial-T000376_Team-TM000050_Member-na_CondBtwn-ASI-ALL_CondWin-na_Vers-1.metadata" \
  "gs://studies.aptima.com/study-3_spiral-1_pilot/NotHSRData_TrialMessages_Trial-T000377_Team-TM000050_Member-na_CondBtwn-ASI-ALL_CondWin-na_Vers-1.metadata" \
  .

**Comment by remo-help** [comment]
I ran the evaluation app on these, and it seemed to only have extracted pre-game chatter. In fact, most of these do not seem to contain any utterance strings or Odin labels at all.

**Comment by adarshp** [comment]
@remo-help - regarding your questions:

1. The speechAnalyzer agent publishes both intermediate and final transcriptions. As the participant is speaking, Google generates intermediate transcriptions continuously until a pause is detected, at which point a final transcription is returned. You will only want to look at the final transcriptions, which are published on the `agent/asr/final` topic. You can also distinguish intermediate transcriptions from final transcriptions by using the key data.is_final, which will be `false` for intermediate transcriptions, and `true` for final transcriptions.

**Comment by adarshp** [comment]
@remo-help as to your second question - yes, those are the files to analyze. I am surprised that they contain only pre-game chatter. I'll take a look into them.

**Comment by adarshp** [comment]
@remo-help - you are right, there is only pre-game chatter. I'll report this issue to TA3. You don't need to continue the evaluation. Thanks for catching this!

**Comment by remo-help** [comment]
I was only looking at the raw metadata file because the evaluation script that Becky wrote only extracted the pregame chatter, wonder what happened there

**Comment by adarshp** [comment]
> I was only looking at the raw metadata file because the evaluation script that Becky wrote only extracted the pregame chatter, wonder what happened there

Fair enough...it seems like the audio capture system wasn't fully functional for some reason. I'll look into it further.
