### ISSUE TITLE
Webapp broken in new master

### ISSUE THREAD

**Issue by remo-help** [clulab/tomcat-text#215]
@Yuweien noticed that the webapp is currently broken. When the webapp is run, it throws the following error:

> [info] Compiling 1 Scala source to /Users/remonitschke/IdeaProjects/tomcat-text/webapp/target/scala-2.12/classes ...
> [error] /Users/remonitschke/IdeaProjects/tomcat-text/webapp/app/controllers/HomeController.scala:116:25: value dialogAgentVersion is not a member of org.clulab.asist.agents.DialogAgent
> [error]         version = agent.dialogAgentVersion,
> [error]                         ^
> [error] one error found
> [error] (webapp / Compile / compileIncremental) Compilation failed
> [info] Compiling 1 Scala source to /Users/remonitschke/IdeaProjects/tomcat-text/webapp/target/scala-2.12/classes ...
> [error] /Users/remonitschke/IdeaProjects/tomcat-text/webapp/app/controllers/HomeController.scala:116:25: value dialogAgentVersion is not a member of org.clulab.asist.agents.DialogAgent
> [error]         version = agent.dialogAgentVersion,
> [error]                         ^
> [error] one error found
> [error] (webapp / Compile / compileIncremental) Compilation failed
> [error] application - 

@jastier I believe, this might be a result of the most recent PR on your side. Is that a possibility? There were some changes to the version of the dialog agent.

**Comment by jastier** [comment]
Yes, that's from my latest update.   Fixing it now.

**Comment by remo-help** [comment]
Thanks!

**Comment by remo-help** [comment]
@Yuweien should work now

**Comment by jastier** [comment]
The issue was fixed by having the HomeController read our software release version number directly from the BuildInfo struct.
The version has been set to 3.1.3.
Merge master into your feature branch to get the change.

**Comment by Yuweien** [comment]
Thank you!
