### ISSUE TITLE
Connecting ASR agent to tomcat chatbot

### ISSUE THREAD

**Issue by adarshp** [clulab/tomcat-text#22]
Now that we have a [prototype ASR agent](https://github.com/clulab/tomcat-speech/tree/master/agents/asr) that can publish transcriptions to the message bus, let's try to have the text analysis agent be able to consume the outputs of the ASR agent.

**Steps**:

- [x] Install the prerequisites for the ASR agent running with the default PocketSphinx engine (I think [this script](https://github.com/clulab/tomcat-speech/blob/master/agents/asr/install_pocketsphinx_python) should do the trick).
- [x] Test the running of the ASR agent by running it in one terminal and subscribing to the `agents/asr_agent` topic using `mosquitto_sub` in another terminal window.
- [x] Once you've tested that it runs properly (contact me if you run into any issues), see if you can get the Dockerized chatbot to process the messages produced by the ASR agent.

**Comment by jastier** [comment]
Done.
