### ISSUE TITLE
Add JSON schema for text analysis agent output messages

### ISSUE THREAD

**Issue by adarshp** [clulab/tomcat-text#23]
@jastier - could you please add a markdown file and a JSON schema for the text analysis agent output messages? You can use the ones [here](https://gitlab.asist.aptima.com/asist/testbed/-/tree/master/MessageSpecs/Chat) as templates.

As for the location, perhaps these can go in a top-level folder called `message_specs`.

**Comment by jastier** [comment]
I wrote a very preliminary JSON schema for the messages here:   https://github.com/clulab/tomcat-text/tree/dialog_agent_edits/message_specs 
Some of the fields are just placeholder String datatypes for now.

**Comment by adarshp** [comment]
@jastier This looks mostly good - just a couple of small changes are required. In this line: https://github.com/clulab/tomcat-text/blob/88e07d1f525f876ef513546ff5cb10bdfdfd1cdc/message_specs/chat_analysis_message.json#L16

you'll need to change `header.json` to header/header.json` (and similarly for lines 19 and 22). Thanks!
