### ISSUE TITLE
Including attachment types in JSON serialization

### ISSUE THREAD

**Issue by adarshp** [clulab/tomcat-text#278]
Issue #274 makes me think that there is another deficiency in the way we are serializing attachments to JSON right now. Namely, the type of the attachment is nowhere to be seen. We should add it to the JSON for an attachment with the key `type`. Issue #274 may have not been as hard to debug if instead of this:

```json
{"value": true}
```

we had

```json
{"type": "Negation", "value": true}
```

**Comment by jastier** [comment]
"type" is a reserved word in Scala.   
We're going to need another variable name.

**Comment by kwalcock** [comment]
If you really want to stick with it: https://stackoverflow.com/questions/8198797/is-there-a-way-to-use-type-word-as-a-variable-name-in-scala

**Comment by adarshp** [comment]
Thanks @kwalcock !

**Comment by jastier** [comment]
And I have learned another scala trick:

![image](https://user-images.githubusercontent.com/8905715/162541502-b0fc8960-a13b-46e6-b2c7-6611efe69b6f.png)

Thanks Keith!

**Comment by jastier** [comment]
Done and on the master branch.
