### ISSUE TITLE
Metadata to Transcript matching

### ISSUE THREAD

**Issue by pelovett** [clulab/tomcat-text#3]
Previous code logic required that the user passed in a direct path to the transcript file and a direct path to the associated metadata file. When processing entire directories of transcripts, there needs to be logic to align transcripts to metadata files. As far as I can tell, the names of the two file types do not perfectly match, so some sort of heuristic or fuzzy matching will need to be implemented.

**Comment by adarshp** [comment]
This is not necessary anymore with the new ASR architecture.
