### ISSUE TITLE
Set of questions not recognized by Odin

### ISSUE THREAD

**Issue by SalenaAshton** [clulab/tomcat-text#310]
Repo last pulled: 8 July 2022

Odin is not extracting all questions from observations (study 3) [633 - 638]. Approximately 90%  of questions are extracted (I've annotated questions by hand and entered each into Odin). Below is the terminal output of questions not extracted. First and second entries are tests, followed by all questions not extracted by Odin, and concludes with final test.

> there is a green victim
{"labels":["Green","Player","Entity","Concept"],"span":"green","arguments":{},"attachments":[],"start_offset":11,"end_offset":16,"rule":"green"}
{"labels":["KnowledgeSharing","Communicate","SimpleAction","Action","EventLike","Concept"],"span":"there is a green victim","arguments":{"exists":[{"labels":["Victim","Entity","Concept"],"span":"victim","arguments":{},"attachments":[],"start_offset":17,"end_offset":23,"rule":"victim"}]},"attachments":[],"start_offset":0,"end_offset":23,"rule":"existential"}
{"labels":["Victim","Entity","Concept"],"span":"victim","arguments":{},"attachments":[],"start_offset":17,"end_offset":23,"rule":"victim"}

> wait, you said i4, c8 and which other room
{"labels":["I4","Room","Infrastructure","Location","EventLike","Concept"],"span":"i4","arguments":{},"attachments":[],"start_offset":15,"end_offset":17,"rule":"room_i4"}
{"labels":["C8","Room","Infrastructure","Location","EventLike","Concept"],"span":"c8","arguments":{},"attachments":[],"start_offset":19,"end_offset":21,"rule":"room_c8"}

> which other was cancelled

> which rooms have the most people

> if you guys are okay with that

> I'm sorry, which rooms?

> sorry, tranporter. Did you?

> sorry, tranporter. Did you?there's two in this area, you said?

> there's two in this area, you said?

> you said you were in one of the k rooms?

> which room are you in currently?

> what do you guys think?

> you mean continue to transport, correct?

> can you type that?

> what room is that?

> or the i row as a whole?

> you said i4-a was one of them? correct?

> any clearing up needing done?

> wait, wouldn't that be a c because he was critical?

> which room are you in?

> which room?

> we cleared out the entire c section, right?

> you're saying it's clear?

> do those match any of your guys' high-traffic places?

> both of these are critical?

> is the one you just handed me a crit?

> so we're going out to what next, since we already cleared d, right?

> are all of these in the same room?

> which room are you guys in right now?

> which room?

> are there any there?

> What is my favorite taco?
{"labels":["Question","Communicate","SimpleAction","Action","EventLike","Concept"],"span":"What is my favorite taco","arguments":{"topic":[{"labels":["Concept"],"span":"taco","arguments":{},"attachments":[],"start_offset":20,"end_offset":24,"rule":"allTokens"}]},"attachments":[],"start_offset":0,"end_offset":24,"rule":"information_gathering_question_that2"}

**Comment by remo-help** [comment]
@SalenaAshton 
Thanks for raising these. Looking at it briefly, a few of these are virtually impossible for us to capture as questions because they depend on context or pitch.
Many of these we can fix, but will probably not be able to do so before August

**Comment by remo-help** [comment]
@Yuweien
