### ISSUE TITLE
Processors, etc

### ISSUE THREAD

**Issue by BeckySharp** [clulab/tomcat-text#34]
I noticed some things that should be fixed sometime soon:

1. The processor in the ieSystem should have coref in it, so we shouldn't need the Stanford parser (https://github.com/clulab/tomcat-text/blob/a9851c32ef32194e680c889b6b7999173a099202/src/main/scala/org/clulab/asist/Extractor.scala#L20) 
a nice thing about this is that then we'll use less memory and it will be faster bc you won't be annotating twice.
2. we should use a case class for the return type you want (rather than a tuple -- which is what you're essentially making with the `Array`) (https://github.com/clulab/tomcat-text/blob/a9851c32ef32194e680c889b6b7999173a099202/src/main/scala/org/clulab/asist/Extractor.scala#L109)
-- this also would simplify this: https://github.com/clulab/tomcat-text/blob/a9851c32ef32194e680c889b6b7999173a099202/src/main/scala/org/clulab/asist/DialogAgent.scala#L50
I would personally also return a `Seq` instead of an ArrayBuffer, as (i think) the latter is a type of the former, so the compiler will still be happy to have an ArrayBuffer satisfy the Seq type requirement (that way it's immutable outside the scope of the method)

**Comment by jastier** [comment]
Works for me.

I'm not a fan of mutables, nor asInstanceOf calls.

-Joseph

**Comment by pelovett** [comment]
Alright, I've removed the transcript ID argument from "runExtraction" and edited all calls to remove the argument.  The changes have been made on this branch:
[pull_request](https://github.com/clulab/tomcat-text/pull/36)

Everything is now more consistently typed and cleaner.

**Comment by jastier** [comment]
Nice!

**Comment by BeckySharp** [comment]
thanks! that was fast, sir!

**Comment by pelovett** [comment]
This issue was solved by the branch that was merged into master. Closing the issue now.
