### ISSUE TITLE
Reduce verbosity of DialogAgent

### ISSUE THREAD

**Issue by adarshp** [clulab/tomcat-text#66]
The current default logging setting for the DialogAgent is too verbose - it prints out each received message and each published message to standard output. TA3 is planning to preserve agent logs from experimental runs - this is going to fill up a large amount of storage.

I suggest printing this information when the log level is DEBUG, rather than INFO.

**Comment by jastier** [comment]
PR is ready now, from branch 'reduce_verbosity'
