### ISSUE TITLE
Dockerized chat agent stub

### ISSUE THREAD

**Issue by adarshp** [clulab/tomcat-text#7]
@jastier As we discussed earlier, we'll need to create Dockerized agents that communicate with an MQTT message bus. The first one we'll tackle is a natural language text processing agent.

Basically, I'm thinking this agent will take the form of a Scala App (like the existing `ExtractInfoSearch` and `ExtractDirSearch` apps whose class files live in the `src/main/scala/org/clulab/asist` directory).

Could you please write a Scala MQTT client app -  maybe call it `DialogueAgent` (unless there's a better name - thoughts, @BeckySharp , @pelovett ?) - that resides under `src/main/scala/org/clulab/asist` that continuously listens to a particular topic on an MQTT message bus, and for each incoming message on that topic, posts an acknowledgment to a different topic on the same message bus (you can make up fake topic names for now)?

This seems like a promising library for writing the client app: https://doc.akka.io/docs/alpakka/current/mqtt-streaming.html . 

But before jumping in, I recommend going through this short writeup I wrote a little while ago that introduces message buses and how to work with them: https://ml4ai.github.io/tomcat/developer/message_bus.html

Once this is done, we'll take the next steps of connecting this stub app to the rest of the NLP text processing code and then Dockerizing it.

**Comment by jastier** [comment]
OK, will do

**Comment by jastier** [comment]
Done.

**Comment by adarshp** [comment]
Closed by #16 .
