### ISSUE TITLE
Sight rule too broad?

### ISSUE THREAD

**Issue by BeckySharp** [clulab/tomcat-text#87]
I think that this isn't sufficient for a "Sight" mention.  thoughts?
![image](https://user-images.githubusercontent.com/5384073/117996979-74bad680-b2f7-11eb-9a15-02639aa34ca1.png)

**Comment by adarshp** [comment]
I agree.

**Comment by remo-help** [comment]
yes, agree, this needs a rework. I will put it on my list

**Comment by remo-help** [comment]
I looked into this, there seem to be multiple things going on. 

- We have a regular sight rule that does not work at all (but Im not sure why)
- We have two "sight_presence" rules. They seem to be intended for existential constructions like "There is a victim in room 2". These are the ones which trigger liberally.

I can fix the regulary sight rule, the question is what do we want to do about the "sight_presence" rules? I can constrain them to work only in the existential context, or we can scrap them altogether.

**Comment by remo-help** [comment]
I fixed the regular sight rule for now (it wasnt working at all, even for "I see the victim"). We should probably discuss the existential case in the next meeting

**Comment by remo-help** [comment]
note to self: refer to meeting notes on how to proceed on this issue

**Comment by remo-help** [comment]
issue resolved

**Comment by BeckySharp** [comment]
in future, in the PR you can add something like:
```closes #87``` as the last line and it will automatically close the issue when the PR is merged, fyi

**Comment by remo-help** [comment]
oh that's neat, thanks
